wireplumber.components = [
  {
    name = boot-volume-pins.lua, type = script/lua
    provides = custom.boot-volume-pins
  }
]

wireplumber.profiles = {
  main = {
    custom.boot-volume-pins = required
  }
}
