  - !cpuload
      interval: 3
      invalid: ''
      prefix: ' '
      prefix_color: '#4080a0'
      separator_width: 12
      suffix: '%'
      color: '#CCCCCC'
      threshold_fix: true
      thresholds:
        0: '#CCCCCC'
        50: '#FFF600'
        80: '#FF0000'

  - !temperature
      sensor: '/tmp/cputemp'
      prefix: ' '
      prefix_color: '#4080a0'
      separator_width: 12
      suffix: ' °C'
      interval: 3
      color: '#CCCCCC'
      threshold_fix: true
      thresholds:
        0: '#CCCCCC'
        60: '#FFF600'
        70: '#FF0000'

  - !memory
      prefix: ' '
      prefix_color: '#4080a0'
      separator_width: 12
      suffix: '%'
      interval: 5
      color: '#CCCCCC'
      threshold_fix: true
      thresholds:
        0: '#CCCCCC'
        40: '#FFF600'
        70: '#FF0000'

  - !filesystem
      path: '/tmp'
      interval: 5
      prefix: ' '
      prefix_color: '#4080a0'
      separator_width: 12
      suffix: '%'
      color: '#CCCCCC'
      threshold_fix: true
      thresholds:
        0: '#CCCCCC'
        40: '#FFF600'
        70: '#FF0000'

  - !filesystem
      path: '/'
      interval: 30
      prefix: ' '
      prefix_color: '#4080a0'
      separator_width: 12
      suffix: '%'
      color: '#CCCCCC'
      threshold_fix: true
      thresholds:
        0: '#CCCCCC'
        50: '#FFF600'
        70: '#FF0000'

  - !volume
      mixer: 'Master'
      alsa_jack_switch_outputs: true
      alsa_jack_mute_on_unplug: true
      alsa_jack_unmute_on_plug: true
      suffix: '%'
      prefix_color: '#4080a0'
      separator_width: 12
      invalid: '♪ muted'
      invalid_color: '#FFF600'
      jack_icons: [' ', ' ']
      jack_only: ['Astell&Kern PEE51 USB Audio', 'Zorloo Ztella USB Audio', 'IBASSO-DC-Series']
      color: '#CCCCCC'
      
  - !custom
      signal: 9
      command: '/opt/bin/weather'
      invalid: 'n/a'
      invalid_color: '#CCCCCC'
      separator_width: 12

  - !custom
      signal: 5
      prefix: " "
      prefix_color: '#4080a0'
      separator_width: 12
      command: '/opt/bin/kbd_layout'

  - !network
      interval: 5
      wifi: ''
      ethernet: ''
      color: '#00CC00'
      separator_width: 12
      invalid: ''
      invalid_color: '#FF0000'
      threshold_fix: true
      thresholds:
        0: '#FF0000'
        20: '#FFAE00'
        50: '#FFF600'
        80: '#00FF00'

  - !custom
      signal: 8
      command: '/opt/bin/vpn'
      invalid: 'n/a'
      invalid_color: '#CCCCCC'
      separator_width: 12

  - !battery
      sensor: '/sys/class/power_supply/BAT1'
      interval: 10
      invalid: 'no battery'
      prefix_color: '#4080a0'
      separator_width: 12
      statuses:
        offline:
          prefix: ' '
          suffix: '%'
        online:
          prefix: ' '
          suffix: '%'
        full:
          prefix: ' '
          suffix: '%'
      color: '#FFFFFF'
      threshold_fix: true
      thresholds:
        0: '#FF0000'
        15: '#FFF600'
        30: '#FFFFFF'
      warning_level: 10
      warning_action: 'systemctl suspend'

  - !time
      prefix: ' '
      prefix_color: '#4080a0'
      separator_width: 8
      format: '%a, %B, %d  %H:%M'
      interval: 1
      color: '#CCCCCC'
