config:
  - cpuload:
      interval: 3
      prefix: " "
      suffix: "%"
      thresholds:
        - threshold: 0
          color: '#FFFFFF'
        - threshold: 50
          color: '#FFF600'
        - threshold: 80
          color: '#FF0000'

  - temperature:
      sensor: '/tmp/cputemp'
      prefix: " "
      suffix: " °C"
      interval: 3
      thresholds:
        - threshold: 0
          color: '#FFFFFF'
        - threshold: 60
          color: '#FFF600'
        - threshold: 70
          color: '#FF0000'

  - memory:
      prefix: ' '
      suffix: '%'
      interval: 5
      thresholds:
        - threshold: 0
          color: '#FFFFFF'
        - threshold: 40
          color: '#FFF600'
        - threshold: 70
          color: '#FF0000'


  - filesystem:
      path: '/tmp'
      interval: 5
      prefix: ' '
      suffix: '%'
      thresholds:
        - threshold: 0
          color: '#FFFFFF'
        - threshold: 40
          color: '#FFF600'
        - threshold: 70
          color: '#FF0000'

  - filesystem:
      path: '/'
      interval: 5
      prefix: ' '
      suffix: '%'
      thresholds:
        - threshold: 0
          color: '#FFFFFF'
        - threshold: 40
          color: '#FFF600'
        - threshold: 70
          color: '#FF0000'

  - volume:
      mixer: 'Master'
      signal: 10
      suffix: '%'
      invalid: "♪ muted"
      invalid_color: "#FFF600"
      prefix_extras: [" ", " "]

  - custom:
      command: '/opt/bin/weather'
      invalid: 'no data'
      interval: 3600
      retry: 10

  - wifi:
      interface: "wlp107s0"
      interval: 4
      prefix: " "
      suffix: "%"
      invalid: "off"
      invalid_color: "#FF0000"
      thresholds:
        - threshold: 0
          color: '#FF0000'
        - threshold: 40
          color: '#FFAE00'
        - threshold: 60
          color: '#FFF600'
        - threshold: 80
          color: '#00FF00'

  - battery:
      sensor: '/sys/class/power_supply/BAT1'
      interval: 10
      full: 100
      invalid: "no battery"
      suffix: '%'
      statuses:
        offline:
          prefix: ' '
        online:
          prefix: '⚡ '
        full:
          prefix: ' '
      thresholds:
        - threshold: 0
          color: '#FF0000'
        - threshold: 15
          color: '#FFF600'
        - threshold: 30
          color: '#FFFFFF'

  - time:
      format: '%d.%m.%Y %H:%M'
      interval: 1


